//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace layout
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSCONGVIEC
    {
        public string ID { get; set; }
        public string CONGVIEC { get; set; }
        public Nullable<double> LUONG { get; set; }
    }
}
