
namespace layout
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.panel1 = new System.Windows.Forms.Panel();
            this.btnBanhang = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnKhachhang = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnTaikhoan = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnExit = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnHoadon = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnSanpham = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnTrangchu = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.panel2 = new System.Windows.Forms.Panel();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.label2 = new System.Windows.Forms.Label();
            this.pageSetupDialog1 = new System.Windows.Forms.PageSetupDialog();
            this.panelDesktop = new System.Windows.Forms.Panel();
            this.btnNhanvien = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.panel1.SuspendLayout();
            this.panel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.panel1.Controls.Add(this.btnNhanvien);
            this.panel1.Controls.Add(this.btnBanhang);
            this.panel1.Controls.Add(this.btnKhachhang);
            this.panel1.Controls.Add(this.btnTaikhoan);
            this.panel1.Controls.Add(this.btnExit);
            this.panel1.Controls.Add(this.btnHoadon);
            this.panel1.Controls.Add(this.btnSanpham);
            this.panel1.Controls.Add(this.btnTrangchu);
            this.panel1.Controls.Add(this.panel2);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Left;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(200, 745);
            this.panel1.TabIndex = 0;
            // 
            // btnBanhang
            // 
            this.btnBanhang.AllowAnimations = true;
            this.btnBanhang.AllowMouseEffects = true;
            this.btnBanhang.AllowToggling = true;
            this.btnBanhang.AnimationSpeed = 200;
            this.btnBanhang.AutoGenerateColors = false;
            this.btnBanhang.AutoRoundBorders = false;
            this.btnBanhang.AutoSizeLeftIcon = true;
            this.btnBanhang.AutoSizeRightIcon = true;
            this.btnBanhang.BackColor = System.Drawing.Color.Transparent;
            this.btnBanhang.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnBanhang.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnBanhang.BackgroundImage")));
            this.btnBanhang.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBanhang.ButtonText = "Bán hàng";
            this.btnBanhang.ButtonTextMarginLeft = 0;
            this.btnBanhang.ColorContrastOnClick = 45;
            this.btnBanhang.ColorContrastOnHover = 45;
            this.btnBanhang.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnBanhang.CustomizableEdges = borderEdges2;
            this.btnBanhang.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnBanhang.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnBanhang.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnBanhang.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnBanhang.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnBanhang.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnBanhang.ForeColor = System.Drawing.Color.White;
            this.btnBanhang.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnBanhang.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnBanhang.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnBanhang.IconMarginLeft = 11;
            this.btnBanhang.IconPadding = 10;
            this.btnBanhang.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnBanhang.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnBanhang.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnBanhang.IconSize = 25;
            this.btnBanhang.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnBanhang.IdleBorderRadius = 40;
            this.btnBanhang.IdleBorderThickness = 1;
            this.btnBanhang.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnBanhang.IdleIconLeftImage = global::layout.Properties.Resources.icons8_teaser_50;
            this.btnBanhang.IdleIconRightImage = null;
            this.btnBanhang.IndicateFocus = true;
            this.btnBanhang.Location = new System.Drawing.Point(12, 306);
            this.btnBanhang.Margin = new System.Windows.Forms.Padding(3, 10, 3, 3);
            this.btnBanhang.Name = "btnBanhang";
            this.btnBanhang.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnBanhang.OnDisabledState.BorderRadius = 40;
            this.btnBanhang.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBanhang.OnDisabledState.BorderThickness = 1;
            this.btnBanhang.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnBanhang.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnBanhang.OnDisabledState.IconLeftImage = null;
            this.btnBanhang.OnDisabledState.IconRightImage = null;
            this.btnBanhang.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(119)))), ((int)(((byte)(215)))));
            this.btnBanhang.onHoverState.BorderRadius = 40;
            this.btnBanhang.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBanhang.onHoverState.BorderThickness = 1;
            this.btnBanhang.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(119)))), ((int)(((byte)(215)))));
            this.btnBanhang.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnBanhang.onHoverState.IconLeftImage = null;
            this.btnBanhang.onHoverState.IconRightImage = null;
            this.btnBanhang.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnBanhang.OnIdleState.BorderRadius = 40;
            this.btnBanhang.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBanhang.OnIdleState.BorderThickness = 1;
            this.btnBanhang.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnBanhang.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnBanhang.OnIdleState.IconLeftImage = global::layout.Properties.Resources.icons8_teaser_50;
            this.btnBanhang.OnIdleState.IconRightImage = null;
            this.btnBanhang.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnBanhang.OnPressedState.BorderRadius = 40;
            this.btnBanhang.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBanhang.OnPressedState.BorderThickness = 1;
            this.btnBanhang.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnBanhang.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnBanhang.OnPressedState.IconLeftImage = null;
            this.btnBanhang.OnPressedState.IconRightImage = null;
            this.btnBanhang.Size = new System.Drawing.Size(178, 40);
            this.btnBanhang.TabIndex = 9;
            this.btnBanhang.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnBanhang.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnBanhang.TextMarginLeft = 0;
            this.btnBanhang.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnBanhang.UseDefaultRadiusAndThickness = true;
            this.btnBanhang.Click += new System.EventHandler(this.btnBanhang_Click);
            // 
            // btnKhachhang
            // 
            this.btnKhachhang.AllowAnimations = true;
            this.btnKhachhang.AllowMouseEffects = true;
            this.btnKhachhang.AllowToggling = true;
            this.btnKhachhang.AnimationSpeed = 200;
            this.btnKhachhang.AutoGenerateColors = false;
            this.btnKhachhang.AutoRoundBorders = false;
            this.btnKhachhang.AutoSizeLeftIcon = true;
            this.btnKhachhang.AutoSizeRightIcon = true;
            this.btnKhachhang.BackColor = System.Drawing.Color.Transparent;
            this.btnKhachhang.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnKhachhang.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnKhachhang.BackgroundImage")));
            this.btnKhachhang.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnKhachhang.ButtonText = "Khách hàng";
            this.btnKhachhang.ButtonTextMarginLeft = 0;
            this.btnKhachhang.ColorContrastOnClick = 45;
            this.btnKhachhang.ColorContrastOnHover = 45;
            this.btnKhachhang.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnKhachhang.CustomizableEdges = borderEdges3;
            this.btnKhachhang.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnKhachhang.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnKhachhang.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnKhachhang.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnKhachhang.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnKhachhang.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnKhachhang.ForeColor = System.Drawing.Color.White;
            this.btnKhachhang.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnKhachhang.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnKhachhang.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnKhachhang.IconMarginLeft = 11;
            this.btnKhachhang.IconPadding = 10;
            this.btnKhachhang.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnKhachhang.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnKhachhang.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnKhachhang.IconSize = 25;
            this.btnKhachhang.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnKhachhang.IdleBorderRadius = 40;
            this.btnKhachhang.IdleBorderThickness = 1;
            this.btnKhachhang.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnKhachhang.IdleIconLeftImage = global::layout.Properties.Resources.icons8_customer_64;
            this.btnKhachhang.IdleIconRightImage = null;
            this.btnKhachhang.IndicateFocus = true;
            this.btnKhachhang.Location = new System.Drawing.Point(12, 412);
            this.btnKhachhang.Margin = new System.Windows.Forms.Padding(3, 10, 3, 3);
            this.btnKhachhang.Name = "btnKhachhang";
            this.btnKhachhang.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnKhachhang.OnDisabledState.BorderRadius = 40;
            this.btnKhachhang.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnKhachhang.OnDisabledState.BorderThickness = 1;
            this.btnKhachhang.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnKhachhang.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnKhachhang.OnDisabledState.IconLeftImage = null;
            this.btnKhachhang.OnDisabledState.IconRightImage = null;
            this.btnKhachhang.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(119)))), ((int)(((byte)(215)))));
            this.btnKhachhang.onHoverState.BorderRadius = 40;
            this.btnKhachhang.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnKhachhang.onHoverState.BorderThickness = 1;
            this.btnKhachhang.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(119)))), ((int)(((byte)(215)))));
            this.btnKhachhang.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnKhachhang.onHoverState.IconLeftImage = null;
            this.btnKhachhang.onHoverState.IconRightImage = null;
            this.btnKhachhang.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnKhachhang.OnIdleState.BorderRadius = 40;
            this.btnKhachhang.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnKhachhang.OnIdleState.BorderThickness = 1;
            this.btnKhachhang.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnKhachhang.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnKhachhang.OnIdleState.IconLeftImage = global::layout.Properties.Resources.icons8_customer_64;
            this.btnKhachhang.OnIdleState.IconRightImage = null;
            this.btnKhachhang.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnKhachhang.OnPressedState.BorderRadius = 40;
            this.btnKhachhang.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnKhachhang.OnPressedState.BorderThickness = 1;
            this.btnKhachhang.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnKhachhang.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnKhachhang.OnPressedState.IconLeftImage = null;
            this.btnKhachhang.OnPressedState.IconRightImage = null;
            this.btnKhachhang.Size = new System.Drawing.Size(178, 40);
            this.btnKhachhang.TabIndex = 8;
            this.btnKhachhang.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnKhachhang.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnKhachhang.TextMarginLeft = 0;
            this.btnKhachhang.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnKhachhang.UseDefaultRadiusAndThickness = true;
            this.btnKhachhang.Click += new System.EventHandler(this.btnKhachhang_Click);
            // 
            // btnTaikhoan
            // 
            this.btnTaikhoan.AllowAnimations = true;
            this.btnTaikhoan.AllowMouseEffects = true;
            this.btnTaikhoan.AllowToggling = true;
            this.btnTaikhoan.AnimationSpeed = 200;
            this.btnTaikhoan.AutoGenerateColors = false;
            this.btnTaikhoan.AutoRoundBorders = false;
            this.btnTaikhoan.AutoSizeLeftIcon = true;
            this.btnTaikhoan.AutoSizeRightIcon = true;
            this.btnTaikhoan.BackColor = System.Drawing.Color.Transparent;
            this.btnTaikhoan.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnTaikhoan.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnTaikhoan.BackgroundImage")));
            this.btnTaikhoan.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTaikhoan.ButtonText = "Tài khoản";
            this.btnTaikhoan.ButtonTextMarginLeft = 0;
            this.btnTaikhoan.ColorContrastOnClick = 45;
            this.btnTaikhoan.ColorContrastOnHover = 45;
            this.btnTaikhoan.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnTaikhoan.CustomizableEdges = borderEdges4;
            this.btnTaikhoan.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnTaikhoan.DisabledBorderColor = System.Drawing.Color.Transparent;
            this.btnTaikhoan.DisabledFillColor = System.Drawing.Color.Transparent;
            this.btnTaikhoan.DisabledForecolor = System.Drawing.Color.Transparent;
            this.btnTaikhoan.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnTaikhoan.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnTaikhoan.ForeColor = System.Drawing.Color.White;
            this.btnTaikhoan.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnTaikhoan.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnTaikhoan.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnTaikhoan.IconMarginLeft = 11;
            this.btnTaikhoan.IconPadding = 10;
            this.btnTaikhoan.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnTaikhoan.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnTaikhoan.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnTaikhoan.IconSize = 25;
            this.btnTaikhoan.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnTaikhoan.IdleBorderRadius = 40;
            this.btnTaikhoan.IdleBorderThickness = 1;
            this.btnTaikhoan.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnTaikhoan.IdleIconLeftImage = global::layout.Properties.Resources.icons8_account_96;
            this.btnTaikhoan.IdleIconRightImage = null;
            this.btnTaikhoan.IndicateFocus = true;
            this.btnTaikhoan.Location = new System.Drawing.Point(12, 465);
            this.btnTaikhoan.Margin = new System.Windows.Forms.Padding(3, 10, 3, 3);
            this.btnTaikhoan.Name = "btnTaikhoan";
            this.btnTaikhoan.OnDisabledState.BorderColor = System.Drawing.Color.Transparent;
            this.btnTaikhoan.OnDisabledState.BorderRadius = 40;
            this.btnTaikhoan.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTaikhoan.OnDisabledState.BorderThickness = 1;
            this.btnTaikhoan.OnDisabledState.FillColor = System.Drawing.Color.Transparent;
            this.btnTaikhoan.OnDisabledState.ForeColor = System.Drawing.Color.Transparent;
            this.btnTaikhoan.OnDisabledState.IconLeftImage = null;
            this.btnTaikhoan.OnDisabledState.IconRightImage = null;
            this.btnTaikhoan.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(119)))), ((int)(((byte)(215)))));
            this.btnTaikhoan.onHoverState.BorderRadius = 40;
            this.btnTaikhoan.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTaikhoan.onHoverState.BorderThickness = 1;
            this.btnTaikhoan.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(119)))), ((int)(((byte)(215)))));
            this.btnTaikhoan.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnTaikhoan.onHoverState.IconLeftImage = null;
            this.btnTaikhoan.onHoverState.IconRightImage = null;
            this.btnTaikhoan.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnTaikhoan.OnIdleState.BorderRadius = 40;
            this.btnTaikhoan.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTaikhoan.OnIdleState.BorderThickness = 1;
            this.btnTaikhoan.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnTaikhoan.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnTaikhoan.OnIdleState.IconLeftImage = global::layout.Properties.Resources.icons8_account_96;
            this.btnTaikhoan.OnIdleState.IconRightImage = null;
            this.btnTaikhoan.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnTaikhoan.OnPressedState.BorderRadius = 40;
            this.btnTaikhoan.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTaikhoan.OnPressedState.BorderThickness = 1;
            this.btnTaikhoan.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnTaikhoan.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnTaikhoan.OnPressedState.IconLeftImage = null;
            this.btnTaikhoan.OnPressedState.IconRightImage = null;
            this.btnTaikhoan.Size = new System.Drawing.Size(178, 40);
            this.btnTaikhoan.TabIndex = 7;
            this.btnTaikhoan.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnTaikhoan.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnTaikhoan.TextMarginLeft = 0;
            this.btnTaikhoan.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnTaikhoan.UseDefaultRadiusAndThickness = true;
            this.btnTaikhoan.Click += new System.EventHandler(this.bunifuButton1_Click);
            // 
            // btnExit
            // 
            this.btnExit.AllowAnimations = true;
            this.btnExit.AllowMouseEffects = true;
            this.btnExit.AllowToggling = true;
            this.btnExit.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.btnExit.AnimationSpeed = 200;
            this.btnExit.AutoGenerateColors = false;
            this.btnExit.AutoRoundBorders = false;
            this.btnExit.AutoSizeLeftIcon = true;
            this.btnExit.AutoSizeRightIcon = true;
            this.btnExit.BackColor = System.Drawing.Color.Transparent;
            this.btnExit.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnExit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnExit.BackgroundImage")));
            this.btnExit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExit.ButtonText = "Đăng xuất";
            this.btnExit.ButtonTextMarginLeft = 0;
            this.btnExit.ColorContrastOnClick = 45;
            this.btnExit.ColorContrastOnHover = 45;
            this.btnExit.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnExit.CustomizableEdges = borderEdges5;
            this.btnExit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnExit.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnExit.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnExit.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnExit.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnExit.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnExit.ForeColor = System.Drawing.Color.White;
            this.btnExit.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnExit.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnExit.IconLeftPadding = new System.Windows.Forms.Padding(30, 3, 3, 3);
            this.btnExit.IconMarginLeft = 11;
            this.btnExit.IconPadding = 10;
            this.btnExit.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnExit.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnExit.IconRightPadding = new System.Windows.Forms.Padding(10, 3, 7, 3);
            this.btnExit.IconSize = 25;
            this.btnExit.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnExit.IdleBorderRadius = 30;
            this.btnExit.IdleBorderThickness = 1;
            this.btnExit.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnExit.IdleIconLeftImage = global::layout.Properties.Resources.icons8_export_64;
            this.btnExit.IdleIconRightImage = null;
            this.btnExit.IndicateFocus = true;
            this.btnExit.Location = new System.Drawing.Point(-16, 694);
            this.btnExit.Margin = new System.Windows.Forms.Padding(10, 10, 3, 3);
            this.btnExit.Name = "btnExit";
            this.btnExit.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnExit.OnDisabledState.BorderRadius = 30;
            this.btnExit.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExit.OnDisabledState.BorderThickness = 1;
            this.btnExit.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnExit.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnExit.OnDisabledState.IconLeftImage = null;
            this.btnExit.OnDisabledState.IconRightImage = null;
            this.btnExit.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(166)))), ((int)(((byte)(48)))));
            this.btnExit.onHoverState.BorderRadius = 30;
            this.btnExit.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExit.onHoverState.BorderThickness = 1;
            this.btnExit.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(166)))), ((int)(((byte)(48)))));
            this.btnExit.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnExit.onHoverState.IconLeftImage = null;
            this.btnExit.onHoverState.IconRightImage = null;
            this.btnExit.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnExit.OnIdleState.BorderRadius = 30;
            this.btnExit.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExit.OnIdleState.BorderThickness = 1;
            this.btnExit.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnExit.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnExit.OnIdleState.IconLeftImage = global::layout.Properties.Resources.icons8_export_64;
            this.btnExit.OnIdleState.IconRightImage = null;
            this.btnExit.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnExit.OnPressedState.BorderRadius = 30;
            this.btnExit.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExit.OnPressedState.BorderThickness = 1;
            this.btnExit.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnExit.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnExit.OnPressedState.IconLeftImage = null;
            this.btnExit.OnPressedState.IconRightImage = null;
            this.btnExit.Size = new System.Drawing.Size(196, 39);
            this.btnExit.TabIndex = 6;
            this.btnExit.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnExit.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnExit.TextMarginLeft = 0;
            this.btnExit.TextPadding = new System.Windows.Forms.Padding(90, 0, 20, 0);
            this.btnExit.UseDefaultRadiusAndThickness = true;
            this.btnExit.Click += new System.EventHandler(this.btnExit_Click);
            // 
            // btnHoadon
            // 
            this.btnHoadon.AllowAnimations = true;
            this.btnHoadon.AllowMouseEffects = true;
            this.btnHoadon.AllowToggling = true;
            this.btnHoadon.AnimationSpeed = 200;
            this.btnHoadon.AutoGenerateColors = false;
            this.btnHoadon.AutoRoundBorders = false;
            this.btnHoadon.AutoSizeLeftIcon = true;
            this.btnHoadon.AutoSizeRightIcon = true;
            this.btnHoadon.BackColor = System.Drawing.Color.Transparent;
            this.btnHoadon.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnHoadon.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnHoadon.BackgroundImage")));
            this.btnHoadon.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHoadon.ButtonText = "Hóa đơn";
            this.btnHoadon.ButtonTextMarginLeft = 0;
            this.btnHoadon.ColorContrastOnClick = 45;
            this.btnHoadon.ColorContrastOnHover = 45;
            this.btnHoadon.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnHoadon.CustomizableEdges = borderEdges6;
            this.btnHoadon.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnHoadon.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnHoadon.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnHoadon.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnHoadon.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnHoadon.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnHoadon.ForeColor = System.Drawing.Color.White;
            this.btnHoadon.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnHoadon.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnHoadon.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnHoadon.IconMarginLeft = 11;
            this.btnHoadon.IconPadding = 10;
            this.btnHoadon.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnHoadon.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnHoadon.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnHoadon.IconSize = 25;
            this.btnHoadon.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnHoadon.IdleBorderRadius = 40;
            this.btnHoadon.IdleBorderThickness = 1;
            this.btnHoadon.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnHoadon.IdleIconLeftImage = global::layout.Properties.Resources.icons8_receipt_approved_50;
            this.btnHoadon.IdleIconRightImage = null;
            this.btnHoadon.IndicateFocus = true;
            this.btnHoadon.Location = new System.Drawing.Point(12, 359);
            this.btnHoadon.Margin = new System.Windows.Forms.Padding(3, 10, 3, 3);
            this.btnHoadon.Name = "btnHoadon";
            this.btnHoadon.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnHoadon.OnDisabledState.BorderRadius = 40;
            this.btnHoadon.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHoadon.OnDisabledState.BorderThickness = 1;
            this.btnHoadon.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnHoadon.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnHoadon.OnDisabledState.IconLeftImage = null;
            this.btnHoadon.OnDisabledState.IconRightImage = null;
            this.btnHoadon.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(119)))), ((int)(((byte)(215)))));
            this.btnHoadon.onHoverState.BorderRadius = 40;
            this.btnHoadon.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHoadon.onHoverState.BorderThickness = 1;
            this.btnHoadon.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(119)))), ((int)(((byte)(215)))));
            this.btnHoadon.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnHoadon.onHoverState.IconLeftImage = null;
            this.btnHoadon.onHoverState.IconRightImage = null;
            this.btnHoadon.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnHoadon.OnIdleState.BorderRadius = 40;
            this.btnHoadon.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHoadon.OnIdleState.BorderThickness = 1;
            this.btnHoadon.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnHoadon.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnHoadon.OnIdleState.IconLeftImage = global::layout.Properties.Resources.icons8_receipt_approved_50;
            this.btnHoadon.OnIdleState.IconRightImage = null;
            this.btnHoadon.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnHoadon.OnPressedState.BorderRadius = 40;
            this.btnHoadon.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHoadon.OnPressedState.BorderThickness = 1;
            this.btnHoadon.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnHoadon.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnHoadon.OnPressedState.IconLeftImage = null;
            this.btnHoadon.OnPressedState.IconRightImage = null;
            this.btnHoadon.Size = new System.Drawing.Size(178, 40);
            this.btnHoadon.TabIndex = 4;
            this.btnHoadon.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnHoadon.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnHoadon.TextMarginLeft = 0;
            this.btnHoadon.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnHoadon.UseDefaultRadiusAndThickness = true;
            this.btnHoadon.Click += new System.EventHandler(this.btnHoadon_Click);
            // 
            // btnSanpham
            // 
            this.btnSanpham.AllowAnimations = true;
            this.btnSanpham.AllowMouseEffects = true;
            this.btnSanpham.AllowToggling = true;
            this.btnSanpham.AnimationSpeed = 200;
            this.btnSanpham.AutoGenerateColors = false;
            this.btnSanpham.AutoRoundBorders = false;
            this.btnSanpham.AutoSizeLeftIcon = true;
            this.btnSanpham.AutoSizeRightIcon = true;
            this.btnSanpham.BackColor = System.Drawing.Color.Transparent;
            this.btnSanpham.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnSanpham.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSanpham.BackgroundImage")));
            this.btnSanpham.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSanpham.ButtonText = "Sản phẩm";
            this.btnSanpham.ButtonTextMarginLeft = 0;
            this.btnSanpham.ColorContrastOnClick = 45;
            this.btnSanpham.ColorContrastOnHover = 45;
            this.btnSanpham.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnSanpham.CustomizableEdges = borderEdges7;
            this.btnSanpham.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSanpham.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnSanpham.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnSanpham.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnSanpham.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSanpham.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnSanpham.ForeColor = System.Drawing.Color.White;
            this.btnSanpham.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSanpham.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSanpham.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSanpham.IconMarginLeft = 11;
            this.btnSanpham.IconPadding = 10;
            this.btnSanpham.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSanpham.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSanpham.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSanpham.IconSize = 25;
            this.btnSanpham.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnSanpham.IdleBorderRadius = 40;
            this.btnSanpham.IdleBorderThickness = 1;
            this.btnSanpham.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnSanpham.IdleIconLeftImage = global::layout.Properties.Resources.icons8_stationery_64;
            this.btnSanpham.IdleIconRightImage = null;
            this.btnSanpham.IndicateFocus = true;
            this.btnSanpham.Location = new System.Drawing.Point(12, 253);
            this.btnSanpham.Margin = new System.Windows.Forms.Padding(3, 10, 3, 3);
            this.btnSanpham.Name = "btnSanpham";
            this.btnSanpham.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnSanpham.OnDisabledState.BorderRadius = 40;
            this.btnSanpham.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSanpham.OnDisabledState.BorderThickness = 1;
            this.btnSanpham.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnSanpham.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnSanpham.OnDisabledState.IconLeftImage = null;
            this.btnSanpham.OnDisabledState.IconRightImage = null;
            this.btnSanpham.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(119)))), ((int)(((byte)(215)))));
            this.btnSanpham.onHoverState.BorderRadius = 40;
            this.btnSanpham.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSanpham.onHoverState.BorderThickness = 1;
            this.btnSanpham.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(119)))), ((int)(((byte)(215)))));
            this.btnSanpham.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSanpham.onHoverState.IconLeftImage = null;
            this.btnSanpham.onHoverState.IconRightImage = null;
            this.btnSanpham.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnSanpham.OnIdleState.BorderRadius = 40;
            this.btnSanpham.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSanpham.OnIdleState.BorderThickness = 1;
            this.btnSanpham.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnSanpham.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSanpham.OnIdleState.IconLeftImage = global::layout.Properties.Resources.icons8_stationery_64;
            this.btnSanpham.OnIdleState.IconRightImage = null;
            this.btnSanpham.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSanpham.OnPressedState.BorderRadius = 40;
            this.btnSanpham.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSanpham.OnPressedState.BorderThickness = 1;
            this.btnSanpham.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSanpham.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSanpham.OnPressedState.IconLeftImage = null;
            this.btnSanpham.OnPressedState.IconRightImage = null;
            this.btnSanpham.Size = new System.Drawing.Size(178, 40);
            this.btnSanpham.TabIndex = 3;
            this.btnSanpham.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSanpham.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSanpham.TextMarginLeft = 0;
            this.btnSanpham.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSanpham.UseDefaultRadiusAndThickness = true;
            this.btnSanpham.Click += new System.EventHandler(this.btnSanpham_Click);
            // 
            // btnTrangchu
            // 
            this.btnTrangchu.AllowAnimations = true;
            this.btnTrangchu.AllowMouseEffects = true;
            this.btnTrangchu.AllowToggling = true;
            this.btnTrangchu.AnimationSpeed = 200;
            this.btnTrangchu.AutoGenerateColors = false;
            this.btnTrangchu.AutoRoundBorders = false;
            this.btnTrangchu.AutoSizeLeftIcon = true;
            this.btnTrangchu.AutoSizeRightIcon = true;
            this.btnTrangchu.BackColor = System.Drawing.Color.Transparent;
            this.btnTrangchu.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnTrangchu.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnTrangchu.BackgroundImage")));
            this.btnTrangchu.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTrangchu.ButtonText = "Trang chủ";
            this.btnTrangchu.ButtonTextMarginLeft = 0;
            this.btnTrangchu.ColorContrastOnClick = 45;
            this.btnTrangchu.ColorContrastOnHover = 45;
            this.btnTrangchu.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btnTrangchu.CustomizableEdges = borderEdges8;
            this.btnTrangchu.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnTrangchu.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnTrangchu.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnTrangchu.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnTrangchu.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnTrangchu.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnTrangchu.ForeColor = System.Drawing.Color.White;
            this.btnTrangchu.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnTrangchu.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnTrangchu.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnTrangchu.IconMarginLeft = 11;
            this.btnTrangchu.IconPadding = 10;
            this.btnTrangchu.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnTrangchu.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnTrangchu.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnTrangchu.IconSize = 25;
            this.btnTrangchu.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnTrangchu.IdleBorderRadius = 40;
            this.btnTrangchu.IdleBorderThickness = 1;
            this.btnTrangchu.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnTrangchu.IdleIconLeftImage = global::layout.Properties.Resources.icons8_home_24;
            this.btnTrangchu.IdleIconRightImage = null;
            this.btnTrangchu.IndicateFocus = true;
            this.btnTrangchu.Location = new System.Drawing.Point(12, 147);
            this.btnTrangchu.Margin = new System.Windows.Forms.Padding(3, 10, 3, 3);
            this.btnTrangchu.Name = "btnTrangchu";
            this.btnTrangchu.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnTrangchu.OnDisabledState.BorderRadius = 40;
            this.btnTrangchu.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTrangchu.OnDisabledState.BorderThickness = 1;
            this.btnTrangchu.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnTrangchu.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnTrangchu.OnDisabledState.IconLeftImage = null;
            this.btnTrangchu.OnDisabledState.IconRightImage = null;
            this.btnTrangchu.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(119)))), ((int)(((byte)(215)))));
            this.btnTrangchu.onHoverState.BorderRadius = 40;
            this.btnTrangchu.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTrangchu.onHoverState.BorderThickness = 1;
            this.btnTrangchu.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(119)))), ((int)(((byte)(215)))));
            this.btnTrangchu.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnTrangchu.onHoverState.IconLeftImage = null;
            this.btnTrangchu.onHoverState.IconRightImage = null;
            this.btnTrangchu.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnTrangchu.OnIdleState.BorderRadius = 40;
            this.btnTrangchu.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTrangchu.OnIdleState.BorderThickness = 1;
            this.btnTrangchu.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnTrangchu.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnTrangchu.OnIdleState.IconLeftImage = global::layout.Properties.Resources.icons8_home_24;
            this.btnTrangchu.OnIdleState.IconRightImage = null;
            this.btnTrangchu.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnTrangchu.OnPressedState.BorderRadius = 40;
            this.btnTrangchu.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTrangchu.OnPressedState.BorderThickness = 1;
            this.btnTrangchu.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnTrangchu.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnTrangchu.OnPressedState.IconLeftImage = null;
            this.btnTrangchu.OnPressedState.IconRightImage = null;
            this.btnTrangchu.Size = new System.Drawing.Size(178, 40);
            this.btnTrangchu.TabIndex = 2;
            this.btnTrangchu.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnTrangchu.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnTrangchu.TextMarginLeft = 0;
            this.btnTrangchu.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnTrangchu.UseDefaultRadiusAndThickness = true;
            this.btnTrangchu.Click += new System.EventHandler(this.btnNhanvien_Click);
            // 
            // panel2
            // 
            this.panel2.Controls.Add(this.pictureBox1);
            this.panel2.Controls.Add(this.label2);
            this.panel2.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel2.Location = new System.Drawing.Point(0, 0);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(200, 95);
            this.panel2.TabIndex = 0;
            // 
            // pictureBox1
            // 
            this.pictureBox1.Image = global::layout.Properties.Resources.fahasa_logo;
            this.pictureBox1.Location = new System.Drawing.Point(12, 36);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(178, 46);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 2;
            this.pictureBox1.TabStop = false;
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.White;
            this.label2.Location = new System.Drawing.Point(16, 9);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(95, 24);
            this.label2.TabIndex = 1;
            this.label2.Text = "Nhà sách ";
            this.label2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // panelDesktop
            // 
            this.panelDesktop.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelDesktop.Location = new System.Drawing.Point(200, 0);
            this.panelDesktop.Name = "panelDesktop";
            this.panelDesktop.Size = new System.Drawing.Size(1267, 745);
            this.panelDesktop.TabIndex = 1;
            // 
            // btnNhanvien
            // 
            this.btnNhanvien.AllowAnimations = true;
            this.btnNhanvien.AllowMouseEffects = true;
            this.btnNhanvien.AllowToggling = true;
            this.btnNhanvien.AnimationSpeed = 200;
            this.btnNhanvien.AutoGenerateColors = false;
            this.btnNhanvien.AutoRoundBorders = false;
            this.btnNhanvien.AutoSizeLeftIcon = true;
            this.btnNhanvien.AutoSizeRightIcon = true;
            this.btnNhanvien.BackColor = System.Drawing.Color.Transparent;
            this.btnNhanvien.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnNhanvien.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnNhanvien.BackgroundImage")));
            this.btnNhanvien.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNhanvien.ButtonText = "Nhân viên";
            this.btnNhanvien.ButtonTextMarginLeft = 0;
            this.btnNhanvien.ColorContrastOnClick = 45;
            this.btnNhanvien.ColorContrastOnHover = 45;
            this.btnNhanvien.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnNhanvien.CustomizableEdges = borderEdges1;
            this.btnNhanvien.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnNhanvien.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnNhanvien.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnNhanvien.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnNhanvien.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnNhanvien.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnNhanvien.ForeColor = System.Drawing.Color.White;
            this.btnNhanvien.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnNhanvien.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnNhanvien.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnNhanvien.IconMarginLeft = 11;
            this.btnNhanvien.IconPadding = 10;
            this.btnNhanvien.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnNhanvien.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnNhanvien.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnNhanvien.IconSize = 25;
            this.btnNhanvien.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnNhanvien.IdleBorderRadius = 40;
            this.btnNhanvien.IdleBorderThickness = 1;
            this.btnNhanvien.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnNhanvien.IdleIconLeftImage = global::layout.Properties.Resources.icons8_staff_100;
            this.btnNhanvien.IdleIconRightImage = null;
            this.btnNhanvien.IndicateFocus = true;
            this.btnNhanvien.Location = new System.Drawing.Point(12, 200);
            this.btnNhanvien.Margin = new System.Windows.Forms.Padding(3, 10, 3, 3);
            this.btnNhanvien.Name = "btnNhanvien";
            this.btnNhanvien.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnNhanvien.OnDisabledState.BorderRadius = 40;
            this.btnNhanvien.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNhanvien.OnDisabledState.BorderThickness = 1;
            this.btnNhanvien.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnNhanvien.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnNhanvien.OnDisabledState.IconLeftImage = null;
            this.btnNhanvien.OnDisabledState.IconRightImage = null;
            this.btnNhanvien.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(119)))), ((int)(((byte)(215)))));
            this.btnNhanvien.onHoverState.BorderRadius = 40;
            this.btnNhanvien.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNhanvien.onHoverState.BorderThickness = 1;
            this.btnNhanvien.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(119)))), ((int)(((byte)(215)))));
            this.btnNhanvien.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnNhanvien.onHoverState.IconLeftImage = null;
            this.btnNhanvien.onHoverState.IconRightImage = null;
            this.btnNhanvien.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnNhanvien.OnIdleState.BorderRadius = 40;
            this.btnNhanvien.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNhanvien.OnIdleState.BorderThickness = 1;
            this.btnNhanvien.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(6)))), ((int)(((byte)(38)))), ((int)(((byte)(111)))));
            this.btnNhanvien.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnNhanvien.OnIdleState.IconLeftImage = global::layout.Properties.Resources.icons8_staff_100;
            this.btnNhanvien.OnIdleState.IconRightImage = null;
            this.btnNhanvien.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnNhanvien.OnPressedState.BorderRadius = 40;
            this.btnNhanvien.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNhanvien.OnPressedState.BorderThickness = 1;
            this.btnNhanvien.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnNhanvien.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnNhanvien.OnPressedState.IconLeftImage = null;
            this.btnNhanvien.OnPressedState.IconRightImage = null;
            this.btnNhanvien.Size = new System.Drawing.Size(178, 40);
            this.btnNhanvien.TabIndex = 10;
            this.btnNhanvien.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnNhanvien.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnNhanvien.TextMarginLeft = 0;
            this.btnNhanvien.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnNhanvien.UseDefaultRadiusAndThickness = true;
            this.btnNhanvien.Click += new System.EventHandler(this.bunifuButton1_Click_1);
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1467, 745);
            this.Controls.Add(this.panelDesktop);
            this.Controls.Add(this.panel1);
            this.MaximumSize = new System.Drawing.Size(1483, 784);
            this.Name = "Form1";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Quản lý ";
            this.Load += new System.EventHandler(this.Form1_Load);
            this.panel1.ResumeLayout(false);
            this.panel2.ResumeLayout(false);
            this.panel2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Panel panel2;
        private System.Windows.Forms.PageSetupDialog pageSetupDialog1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnHoadon;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSanpham;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnTrangchu;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnExit;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Panel panelDesktop;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnTaikhoan;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnKhachhang;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnBanhang;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnNhanvien;
    }
}

