//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace layout
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CTHDs = new HashSet<CTHD>();
            this.DSGIAMGIAs = new HashSet<DSGIAMGIA>();
        }
    
        public string MASANPHAM { get; set; }
        public string TENSANPHAM { get; set; }
        public Nullable<double> GIANHAP { get; set; }
        public Nullable<double> GIABAN { get; set; }
        public Nullable<System.DateTime> NAMSANXUAT { get; set; }
        public string XUATXU { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public string DVT { get; set; }
        public string LOAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DSGIAMGIA> DSGIAMGIAs { get; set; }
        public virtual SACH SACH { get; set; }
    }
}
